settings:
  name: Satori CLI Test
  log: slack

import:
  - "satori://code/trufflehog.yml"
  - "satori://code/semgrep-secrets.yml"
  #- "satori://code/semgrep.yml"
  #- "satori://code/python/pylint.yml"

tests:
  assertReturnCode: 0
  install_satori:
    test:
    - [ pip install . ]

  create_profile:
    assertStdoutContains: "Token saved"
    test:
    - [ satori-cli config token "not_a_token" -p test_user ]

  set_token:
    assertStdoutContains: "Token saved"
    test:
    - [ satori-cli config token "$(TOKEN)" ]

  dashboard:
    test:
    - [ satori-cli ]

  playbook:
    test:
    - [ satori-cli playbook ]

  playbook_public:
    test:
    - [ satori-cli playbook --public ]

  report:
    test:
    - [ satori-cli report ]

  repo:
    test:
    - [ satori-cli repo ]

  monitor:
    test:
    - [ satori-cli monitor ]

  pass:
    test:
    - [ satori-cli run .satori/pass.yml --report ]

  fail:
    assertReturnCode: 1
    test:
    - [ satori-cli run .satori/fail.yml --report ]

  empty:
    assertReturnCode: 1
    test:
    - [ satori-cli run .satori/empty.yml --report ]

  import:
    test:
    - [ satori-cli run .satori/import.yml --sync ]

  run_url:
    test:
    - [ "satori-cli run satori://web/testssl.yml --data=\"{'URL':'https://www.satori-ci.com'}\" --output" ]
