settings:
  name: Satori CLI Test 
  log: slack

import:
  - "satori://code/semgrep-secrets.yml"
  #- "satori://code/semgrep.yml"
  #- "satori://code/python/pylint.yml"

positive:
  assertReturnCode: 0
  install_satori:
    test:
    - [ pip install . ]

  create_profile:
    assertStdoutContains: "Token saved"
    test:
    - [ satori-cli config token "not_a_token" -p test_user ]

  set_token:
    assertStdoutContains: "Token saved"
    test:
    - [ satori-cli config token "$(TOKEN)" ]

  dashboard:
    test:
    - [ satori-cli ]

  run:
    pass_report:
      test:
      - [ satori-cli run .satori/import/pass.yml --report ]

    import_sync:
      test:
      - [ satori-cli run .satori/import --sync ]

    url_output:
      test:
      - [ "satori-cli run satori://web/testssl.yml --data=\"{'URL':'https://www.satori-ci.com'}\" --output" ]

  report:
    assertReturnCode: 0
    list:
      test:
      - [ satori-cli report ]

    new_sync:
    - ["satori-cli run .satori/pass.yml -s | grep 'Report ID' | egrep 'r[a-zA-Z0-9]{15}' -o >> report_id.txt"]

    echo_ID:
    - [ export ID=$(cat report_id.txt); echo $ID ]

    single:
      test:
      - [ export ID=$(cat report_id.txt); satori-cli report $ID ]

    output:
      test:
      - [ export ID=$(cat report_id.txt); satori-cli report $ID output ]

    delete:
      test:
      - [ export ID=$(cat report_id.txt); satori-cli report $ID delete ]

    new_async: # new report for stop is needed because the first one is already stopped
    - ["satori-cli run .satori/import/pass.yml | grep 'Report ID' | egrep 'r[a-zA-Z0-9]{15}' -o >> report_id2.txt"]

    sleep: # wait until start
    - [ sleep 10 ]

    stop:
      test:
      - [ export ID=$(cat report_id2.txt); satori-cli report $ID stop ]

  playbook:
    list:
      test:
      - [ satori-cli playbook ]

    list_public:
      test:
     - [ satori-cli playbook --public ]

    echo:
    - [ export ID=$(cat report_id2.txt); echo $ID ]

    single:
      test:
      - [ export ID=$(cat report_id2.txt); satori-cli playbook $ID ]

    delete:
      test:
      - [ export ID=$(cat report_id2.txt); satori-cli playbook $ID delete ]

  repo:
    list:
      test:
      - [ satori-cli repo ]

    single:
      test:
      - [ satori-cli repo satorici/hello_world ]

    run:
      test:
      - [ satori-cli repo satorici/hello_world run ]
  # TODO: needs sync mode
  # check_commits: 
  #   test:
  #   - [ satori-cli repo satorici/hello_world check_commits ]

  # commits:
  #   test:
  #   - [ satori-cli repo satorici/hello_world commits ]

  # check_forks:
  #   test:
  #   - [ satori-cli repo satorici/hello_world check_forks ]

  # scan:
  #   test:
  #   - [ satori-cli repo satorici/hello_world scan ]

  # scan_stop:
  #   test:
  #   - [ satori-cli repo satorici/hello_world scan-stop ]

  # clean: # needs sync mode
  #   test:
  #   - [ satori-cli repo satorici/hello_world clean ]

  monitor:
    assertReturnCode: 0
    list:
      test:
      - [ satori-cli monitor ]

    new:
    - ["satori-cli run .satori/monitor.yml -s | grep 'Monitor ID' | egrep 'm[a-zA-Z0-9]{15}' -o >> monitor_id.txt"]

    echo:
    - [ export ID=$(cat monitor_id.txt); echo $ID ]

    sleep: # wait until start
    - [ sleep 10 ]

    single:
      test:
      - [ export ID=$(cat monitor_id.txt); satori-cli monitor $ID ]

    start:
      test:
      - [ export ID=$(cat monitor_id.txt); satori-cli monitor $ID start ]

    stop:
      test:
      - [ export ID=$(cat monitor_id.txt); satori-cli monitor $ID stop ]

    delete:
      test:
     - [ export ID=$(cat monitor_id.txt); satori-cli monitor $ID delete ]

  teams:
    assertReturnCode: 0
    list:
      test:
      - [ satori-cli team ]

    clean:
    - [ satori-cli team test_team delete || true ]

    create:
      test:
      - [ satori-cli team test_team create ]

    single:
      test:
      - [ satori-cli team test_team ]

    members:
      test:
      - [ satori-cli team test_team members ]

    add_member:
      test:
      - [ satori-cli team test_team add_member --email="test@satori-ci.com" ]

    del_member:
      test:
      - [ satori-cli team test_team del_member --email="user@satori-ci.com" ]

  repos:
    test:
    - [ satori-cli team test_team repos ]

    add_repo:
      test:
      - [ satori-cli team test_team add_repo --repo="satorici/hello_world" ]

    delete:
      test:
      - [ satori-cli team test_team delete ]

negative:
  assertReturnCode: 1
  fail:
    test:
    - [ satori-cli run .satori/fail.yml --report ]

  empty:
    test:
    - [ satori-cli run .satori/empty.yml --report ]
