settings:
  name: "Satori CLI Tests"
  log: slack
  public: true
  image: public.ecr.aws/docker/library/python:3.9-slim-bullseye

import:
  - "satori://secrets/semgrep.yml"

test:
  assertReturnCode: 0
  assertStderrNotContains: Traceback
  install:
    updates:
      - apt update
    tools:
      - apt install -y --no-install-recommends git jq
    satori:
      - pip install .

  # the -P or --profile parameters allows you to use different Satori CI API Tokens
  token_saved:
    setParallel: true
    create_profile:
      - satori config token "not_a_token" --profile test_user

    # define the default token for the configuration
    set_token:
      - satori config token ${{TOKEN}}

  # show the user's dashboard
  dashboard:
    - satori

  local:
    setParallel: true
    # execute a Satori CI playbook locally and show the report once its done
    pass_report:
      - satori local ./ -p .satori/import/pass.yml --report

    # execute a Satori CI playbook locally on a directory with a .satori.yml playbook
    import_sync:
      - satori local .satori/import --summary

    # execute a public Satori CI playbook locally and pass parameters
    url_output:
      - satori local ./ -p satori://web/testssl.yml --data='{"HOST":"https://satori.ci"}' --output

    # define inputs on your playbook and execute it with different combination of parameters
    input:
      - satori local .satori/input.yml --report --output

  run:
    setParallel: true
    # execute a Satori CI playbook and show the report once its done with 4 CPUs
    pass_report:
      - satori run .satori/import/pass.yml --report --cpu 256 --memory 512

    # execute a Satori CI playbook locally on a directory with a .satori.yml playbook
    import_sync:
      - satori run .satori/import --sync

    # execute a public Satori CI playbook and pass parameters
    url_output:
      - satori run satori://web/testssl.yml --data='{"HOST":"https://satori.ci"}' --output

    # define inputs on your playbook and execute it with different combination of parameters
    input:
      - satori run .satori/input.yml --report --output

  report:
    # run synchronously a local playbook
    new_sync:
      - "satori run .satori/import/pass.yml -s | grep 'Report ID' | grep -E 'r[a-zA-Z0-9]{15}' -o"

    #echo_ID:
    #- [ "export ID=$(cat report_id.txt); echo $ID" ]

    # list the reports generated
    list:
      - satori reports

    # list the pending reports
    filter:
      - satori reports --filter="status=Pending"

    parallel:
      setParallel: true
      # show a report
      single:
        - "satori report ${{test.report.new_sync.stdout.trim()}}"

      # show a json report
      json:
        - "satori report ${{test.report.new_sync.stdout.trim()}} --json"

      # make a report public
      public:
        - "satori report ${{test.report.new_sync.stdout.trim()}} public"

      # show the output associated to a report
      output:
        - "satori report ${{test.report.new_sync.stdout.trim()}} output"

      # download the files associated to a report
      files:
        - "satori report ${{test.report.new_sync.stdout.trim()}} files"

    # delete the files, the output and the report
    delete:
      - "satori report ${{test.report.new_sync.stdout.trim()}} delete"

    # run asynchronously a local playbook
    new_async: # new report for stop is needed because the first one is already stopped
      - "satori run .satori/import/pass.yml | grep 'Report ID' | grep -E 'r[a-zA-Z0-9]{15}' -o"

    # stop a running report
    stop: # wait until start
      - "sleep 10; echo ${{test.report.new_async.stdout.trim()}}; satori report ${{test.report.new_async.stdout.trim()}} stop"

  playbook:
    list:
      setParallel: true
      private:
        - satori playbooks

      public:
        - satori playbooks --public

      monitors:
        - satori playbooks --monitor true

    read:
      setParallel: true
      private_playbook_by_report_id:
        - "echo ${{test.report.new_async.stdout.trim()}}; satori playbook ${{test.report.new_async.stdout.trim()}}"

      private_playbook_by_id:
        - "satori playbooks --json|jq -r '.[0].id'"

      public_playbook:
        - satori playbook satori://secrets/detect-secrets.yml

    public_flag:
      - satori playbook ${{test.playbook.read.private_playbook_by_id.stdout.trim()}} public

    delete_private:
      - satori playbook ${{test.playbook.read.private_playbook_by_id.stdout.trim()}} delete

  repo:
    # list the repositories showing to which team they belong, if they are connected to Github CI, info about the playbook and the latest results obtained
    list:
      - satori repos

    # list the commits and the reports associated to a repository
    single:
      - satori repo satoridev01/hello_world

    # simulate a push from the latest version to run the .satori.yml playbook from the repo
    run:
      - satori repo satoridev01/hello_world run

    # list the commits of a certain repo
    commits:
      - satori repo satoridev01/hello_world commits

    # TODO: get the forks of a certain repo (required for fork-scan)
    #check_forks:
    #  - [satori repo satoridev01/hello_world check-forks]

  monitor:
    # run a new monitor
    new:
      - "satori run .satori/monitor.yml -s | grep 'Monitor ID' | sed 's/\\x1b\\[[0-9;]*m//g' | grep -E 'm[a-zA-Z0-9]{15}' -o"

    # list the monitors
    list:
      - "sleep 5; satori monitors"

    # list the reports associated to a monitor
    single: # wait until start
      - "satori monitor ${{test.monitor.new.stdout.trim()}}"

    # make a monitor's reports public
    public: #
      - "satori monitor ${{test.monitor.new.stdout.trim()}} public"

    # stop a monitor
    start:
      - "satori monitor ${{test.monitor.new.stdout.trim()}} start"

    # start a monitor
    stop:
      - "satori monitor ${{test.monitor.new.stdout.trim()}} stop"

    # delete the reports associated to a monitor
    clean:
      - "satori monitor ${{test.monitor.new.stdout.trim()}} clean"

    # delete the monitor
    delete:
      - "satori monitor ${{test.monitor.new.stdout.trim()}} delete"

  scan:
    # # To be developed: list the current scans
    list:
      - satori scans

    # Get the commits of a certain repo (required for scans)
    check_commits:
      - satori scan satoridev01/hello_world check-commits

    # Run the .satori.yml playbook with a certain coverage on the repo
    run:
      - "satori scan satoridev01/hello_world -c 50 | grep 'id:' | sed 's/\\x1b\\[[0-9;]*m//g' | grep -E 's[a-zA-Z0-9]{15}' -o"

    # What's the status of the current scanning
    status:
      - "satori scan ${{test.scan.run.stdout.trim()}} status"

    # Stop the scan execution
    stop:
      - "satori scan ${{test.scan.run.stdout.trim()}} stop"

    # Restart a scan execution
    # start:
    #   - [satori scan satoridev01/hello_world start]

    # Delete the scan reports
    clean:
      - satori scan satoridev01/hello_world clean

  teams:
    # list teams and repos without teams
    list:
      - satori teams

    # create team 'test_team'
    create:
      - satori team test_team create

    parallel:
      setParallel: true
      # list the repos associated to the 'test_team' and their team members
      single:
        - satori team test_team

      # list the members of the 'test_team'
      members:
        - satori team test_team members

      # list your TEAM members
      settings:
        - satori team test_team settings

      # list your TEAM settings
      get_config:
        - satori team test_team get_config notification_email

    # show your TEAM's config setting for a specific value
    set_config:
      - satori team test_team set_config notification_email test@satori.ci
    # set your TEAM CONFIG setting

    # add the email 'test@satori.ci' as a member of the team 'test_team'
    add_member:
      - satori team test_team add --email='test@satori.ci'

    # delete the email 'test@satori.ci' as a member of the team 'test_team'
    delete_member:
      - satori team test_team del --email='test@satori.ci'

    add_github_member:
      - satori team test_team add --github='satoridev02'

    delete_github_member:
      - satori team test_team del --github='satoridev02'

    # add the repo 'satoridev01/hello_world' to the team 'test_team'
    add_repo:
      - satori team test_team add --repo='satoridev01/hello_world'

    # list the repos associated to the 'test_team'
    team_with_repos:
      - satori team test_team repos

    # delete the repo 'satoridev01/hello_world' from the team 'test_team'
    del_repo:
      - satori team test_team del --repo='satoridev01/hello_world'

    # list the repos associated to the 'test_team'
    team_without_repos:
      - satori team test_team repos

    # delete the 'test_team'
    delete:
      - satori team test_team delete

negative_test:
  assertReturnCodeNot: 0
  assertStderrNotContains:
    - Traceback
  assertStdoutNotContains:
    - malformed node
    - invalid syntax
    - object has no attribute

  run:
    setParallel: true
    fail:
      - satori run .satori/fail.yml --sync

    empty_playbook:
      - satori run .satori/empty.yml --report

    empty_playbook_id:
      - satori playbook

    empty_directory:
      - mkdir test; cd test; satori run ./

    no_dns:
      - "cp /etc/resolv.conf /etc/resolv.conf.bak; echo 'nameserver 0.0.0.0' > /etc/resolv.conf ; satori; RET=$?; cat /etc/resolv.conf.bak > /etc/resolv.conf; return $RET"

    random:
      - "dd if=/dev/urandom of=random_file.yml bs=1024 count=1; satori run random_file.yml --output"

    malformed_or_invalid_json_data:
      - "satori run .satori/empty.yml --data={'A':'B'}; satori run .satori/empty.yml --data={'A':'B','C':'D'}"

    malformed_credentials:
      - cp random_file.yml ~/.satori_credentials.yml; satori
