settings:
  name: Satori CLI Tests
  #report: pdf
  #log: slack

import:
  - "satori://code/trufflehog.yml"
  - "satori://code/semgrep-secrets.yml"
  #- "satori://code/semgrep.yml"
  #- "satori://code/python/pylint.yml"

tests:
  assertReturnCode: 0
  pip_install:
    assertStdoutContains: "Successfully installed satori-ci"
    test:
    - [ pip install . ]

  dashboard:
    assertStdoutContains: "Actions required"
    test:
    - [ satori-cli ]

  config:
    assertStdoutContains: "Token saved"
    token:
    - [ satori-cli config token "$(TOKEN)" ]
    profile:
    - [ satori-cli config token "not_a_token" -p test_user]

  playbook:
    assertStdoutContains: "id: p"
    test:
    - [ satori-cli playbook ]

  report:
    assertStdoutContains: "id: r"
    test:
    - [ satori-cli report ]

  repo:
    assertStdoutContains: "GitHub Repositories"
    test:
    - [ satori-cli repo ]

  monitor:
    assertStdoutContains: "Monitors"
    test:
    - [ satori-cli monitor ]
