[project]
name = "satori-ci"
version = "1.0.1"
description = "Satori CI - Automated Software Testing Platform"
authors = [
    {name = "Satori CI CLI", email = "info@satori-ci.com"},
]
dependencies = [
    "requests>=2.27.1",
    "pyyaml>=6.0",
]
requires-python = ">=3.9"
readme = "README.md"
license = {file = "LICENSE"}

[project.urls]
Homepage = "https://www.satori-ci.com"
[tool.pdm]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"

[project.scripts]
satori-cli = "satorici.satori_module:main"
