[project]
name = "satori-ci"
version = "1.3.3"
description = "Satori CI - Automated Software Testing Platform"
authors = [
    {name = "Satori CI CLI", email = "info@satori-ci.com"},
]
dependencies = [
    "requests>=2.27.1",
    "pyyaml>=6.0",
    "colorama>=0.4.6",
    "flatdict>=4.0.1",
    "rich>=13.0",
    "gitpython>=3.1.31",
    "satori-playbook-validator>=3.0.0",
    "textual>=0.26.0",
    "packaging>=23.1",
    "setuptools>=67.8.0",
    "satori-docs",
]
requires-python = ">=3.9"
readme = "README.md"
license = {file = "LICENSE"}

[project.urls]
Homepage = "https://www.satori-ci.com"
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project.scripts]
satori-cli = "satoricli.cli.parser:main"
