[project]
name = "satori-ci"
version = "1.0.0a"
description = "Satori CI - Automated Software Testing Platform"
authors = [{name = "Satori CI", email = "info@satori-ci.com"}]
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Testing",
]
keywords = ["Satori CI", "Software Testing", "CLI"]
dependencies = [
    "requests>=2.28.1",
    "pyyaml>=6.0",
    "urllib3>=1.26.12",
    "charset-normalizer>=2.1.1",
    "certifi>=2022.9.24",
    "idna>=3.4",
    "wheel"
]
requires-python = ">=3.9"

[project.urls]
Homepage = "https://www.satori-ci.com"

[project.scripts]
satori-ci = "satori-ci.__main__:main"

[tool.pdm]

#[tool.setuptools]
#packages = ["src/satori-ci"]

[build-system]
#requires = ["pdm-pep517>=0.12.0", 
requires = ["setuptools>=61.0.0", "wheel"]
#build-backend = "pdm.pep517.api"
build-backend = "setuptools.build_meta"
