[project]
name = "satori-ci"
version = "0.0.2"
description = "Satori CI - Automated Software Testing Platform"
authors = [
    {name = "Satori CI CLI", email = "info@satori-ci.com"},
]
dependencies = [
    "requests>=2.27.1",
    "pyyaml>=6.0",
]
requires-python = ">=3.9"

[project.urls]
Homepage = "https://www.satori-ci.com"
[tool.pdm]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"

[project.scripts]
satori-ci = "satorici.satori_module:main"

[tool.distutils.bdist_wheel]
universal = true
