#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import sys

from classes.satori import Satori


def main():
    if not (sys.version_info.major == 3 and sys.version_info.minor >= 9):
        print(f"Minimum Python version 3.9 required, the current version is {sys.version_info.major}.{sys.version_info.minor}\nHow To Install Python 3.10 on Ubuntu: https://computingforgeeks.com/how-to-install-python-on-ubuntu-linux-system/")
        sys.exit(0)

    parser = argparse.ArgumentParser(add_help=True, exit_on_error=True)
    sub_parsers = parser.add_subparsers(dest="subcommand")

    # config token "user_token"
    config_cmd = sub_parsers.add_parser("config")
    config_cmd.add_argument("profile", default='default', help="The profile name, uses 'default' by default")
    config_cmd.add_argument("value")

    # run playbook.yml
    run_cmd = sub_parsers.add_parser("run")
    run_cmd.add_argument("playbook")
    run_cmd.add_argument("--profile", dest='profile', type=str, default='default', help="The credentials profile you are using")

    # upload ./directory
    upload_cmd = sub_parsers.add_parser("upload")
    upload_cmd.add_argument("directory")
    upload_cmd.add_argument("--profile", dest='profile', type=str, default='default', help="The credentials profile you are using")

    # playbooks
    playbooks_cmd = sub_parsers.add_parser("playbooks")
    playbooks_cmd.add_argument("--profile", dest='profile', type=str, default='default', help="The credentials profile you are using")

    # stop-report id
    stop_report_cmd = sub_parsers.add_parser("stop-report")
    stop_report_cmd.add_argument("id")
    stop_report_cmd.add_argument("--profile", dest='profile', type=str, default='default', help="The credentials profile you are using")

    # status id
    status_cmd = sub_parsers.add_parser("status")
    status_cmd.add_argument("id")
    status_cmd.add_argument("--profile", dest='profile', type=str, default='default', help="The credentials profile you are using")

    # cron list|stop <report_uuid>|stopall
    cron_cmd = sub_parsers.add_parser("cron")
    cron_cmd.add_argument("action")
    cron_cmd.add_argument("param", default='all', nargs='?')
    cron_cmd.add_argument("--profile", dest='profile', type=str, default='default', help="The credentials profile you are using")

    # scan <repo_url>
    scan_cmd = sub_parsers.add_parser("scan")
    scan_cmd.add_argument("repo_url", help="Github repository")
    scan_cmd.add_argument('-c', '--coverage', dest='coverage', type=float, default=0, help="coverage")
    scan_cmd.add_argument('-s', '--skip-check', dest='skip_check', default=False, action=argparse.BooleanOptionalAction)
    scan_cmd.add_argument('-f', '--from', dest='from_date', type=str, default='', help="From Date")
    scan_cmd.add_argument('-t', '--to', dest='to_date', type=str, default='', help="To Date")
    scan_cmd.add_argument("--profile", dest='profile', type=str, default='default', help="The credentials profile you are using")

    # stop <repo_name|repo_url>
    stop_cmd = sub_parsers.add_parser("stop")
    stop_cmd.add_argument("repo", help="Github repository")
    stop_cmd.add_argument("--profile", dest='profile', type=str, default='default', help="The credentials profile you are using")

    # info <repo_name|repo_url>
    info_cmd = sub_parsers.add_parser("info")
    info_cmd.add_argument("repo", type=str, help="Github repository")
    info_cmd.add_argument("--profile", dest='profile', type=str, default='default', help="The profile you are setting up")

    # ci
    info_cmd = sub_parsers.add_parser("ci")
    info_cmd.add_argument("--profile", dest='profile', type=str, default='default', help="The profile you are setting up")

    # clean <repo_name|repo_url>
    clean_cmd = sub_parsers.add_parser("clean")
    clean_cmd.add_argument("repo", help="Github repository")
    clean_cmd.add_argument('-d', '--delete-commits', dest='delete_commits', default=False, action=argparse.BooleanOptionalAction)
    clean_cmd.add_argument("--profile", dest='profile', type=str, default='default', help="The credentials profile you are using")

    # report <repo_name|repo_url>
    report_cmd = sub_parsers.add_parser("report")
    report_cmd.add_argument("repo", help="Github repository or report UUID")
    report_cmd.add_argument('-p', '--page', dest='page', type=int, default=1, help="Commit page number")
    report_cmd.add_argument('-l', '--limit', dest='limit', type=int, default=20, help="Page limit number")
    report_cmd.add_argument('-f', '--filter', dest='filter', type=str, default='', help="Filters: from,to,satori_error,status")
    report_cmd.add_argument("--profile", dest='profile', type=str, default='default', help="The profile you are setting up")

    # monitor
    monitor_cmd = sub_parsers.add_parser("monitor")
    monitor_cmd.add_argument("--profile", dest='profile', type=str, default='default', help="The profile you are setting up")

    # output
    output_cmd = sub_parsers.add_parser("output")
    output_cmd.add_argument("id", help="Github repository or report UUID")
    output_cmd.add_argument("--profile", dest='profile', type=str, default='default', help="The profile you are setting up")

    argv_len = len(sys.argv)
    # print(f"{sys.argv=}")
    if argv_len <= 1:
        parser.print_help()
        sys.exit(0)
    # elif argv_len in (2,4) and sys.argv[1] == 'info':
        # Add empty string to 'satori-cli info' command
        # sys.argv.append('')

    instance = Satori()
    args = parser.parse_args()
    if args.subcommand == "config":
        instance.save_config(args.profile, args.value)
    elif args.subcommand == "run":
        instance.run(args.playbook, args.profile)
    elif args.subcommand == "upload":
        instance.upload(args.directory, args.profile)
    elif args.subcommand == "playbooks":
        instance.playbooks(args.profile)
    elif args.subcommand == "stop-report":
        instance.stop_report(args.id, args.profile)
    elif args.subcommand == "status":
        instance.report_status(args.id, args.profile)
    elif args.subcommand == "cron":
        instance.cron_action(args.action, args.param, args.profile)
    elif args.subcommand == "scan":
        instance.scan(args.repo_url, args.coverage, args.skip_check, args.from_date, args.to_date, args.profile)
    elif args.subcommand == "stop":
        instance.stop(args.repo, args.profile)
    elif args.subcommand == "info":
        instance.scan_info(args.repo, args.profile)
    elif args.subcommand == "ci":
        instance.ci(args.profile)
    elif args.subcommand == "clean":
        instance.clean(args.repo, args.delete_commits, args.profile)
    elif args.subcommand == "report":
        instance.report_info(args.repo, args.page, args.limit, args.filter, args.profile)
    elif args.subcommand == "monitor":
        instance.monitor(args.profile)
    elif args.subcommand == "output":
        instance.output(args.profile, args.id)


if __name__ == "__main__":
    main()
