.\" Manpage for satori-cli
.\" Contact support@satori-ci.com to correct errors or typos.
.TH man 1 "13 Apr 2023" "1.0" "satori-cli man page"
.SH NAME
Satori CI is an automated testing platform that allows you to test throughout the software lifecycle.

.SH SYNOPSIS

satori-cli [category] [object] [action] [options]

.SH DESCRIPTION

.TP
\fB**Dashboard: /dashboard**\fR


satori-cli                                            # GET /dashboard/


.IP \fB**Config:**\fR


satori-cli config token X                             # no API call


.IP \fB**Repository: /repo/**\fR

satori-cli repo                                             # GET /repo/

satori-cli repo satoridev01/HelloWorld                      # GET /repo/satoridev01/HelloWorld

satori-cli repo satoridev01/HelloWorld commits              # GET /repo/satoridev01/HelloWorld/commits

satori-cli repo satoridev01/HelloWorld check-commits        # GET /repo/satoridev01/HelloWorld/check-commits

satori-cli repo satoridev01/HelloWorld check-forks          # GET /repo/satoridev01/HelloWorld/check-forks

satori-cli repo satoridev01/HelloWorld scan                 # GET /repo/scan/satoridev01/HelloWorld/start

satori-cli repo satoridev01/HelloWorld scan-stop            # GET /repo/scan/satoridev01/HelloWorld/stop

satori-cli repo satoridev01/HelloWorld run                  # GET /repo/scan/runsatoridev01/HelloWorld/last

satori-cli repo satoridev01/HelloWorld/commit123 run        # GET /repo/scan?url=satoridev01/HelloWorld/commit123

satori-cli repo satoridev01/HelloWorld clean                # GET /repo/satoridev01/HelloWorld/clean


.IP \fB**Monitor: /monitor/**\fR

satori-cli monitor                      #    GET /monitor/

satori-cli monitor ABC123               #    GET /monitor/ABC123/

satori-cli monitor ABC123 start         #    PATCH /monitor/ABC123/start

satori-cli monitor ABC123 stop          #    PATCH /monitor/ABC123/stop

satori-cli monitor ABC123 delete        # DELETE /monitor/ABC123/


.IP \fB**Report: /report/**\fR

satori-cli report                       #    GET /report/

satori-cli report DEF456                #    GET /report/DEF456

satori-cli report DEF456 output         #    GET /report/DEF456/output

satori-cli report DEF456 stop           #    GET /report/DEF456/stop

satori-cli report DEF456 delete         # DELETE /report/DEF456


.IP \fB**Run: /run/**\fR

satori-cli run                      #  GET /runs/

satori-cli run playbook.yml         # POST /runs/bundle

satori-cli run ./                   # POST /runs/archive


.IP \fB**Playbook**\fR

satori-cli playbook                     # GET /playbook/

satori-cli playbook GHI456              # GET /playbook/?id=GHI456

satori-cli playbook GHI456 delete       # DELETE /playbook/?id=GHI456


.SH OPTIONS
The following options are available for Satori-CLI:

.TP
\fB--json\fR
Output results in JSON format.

.TP
\fB--filter\fR
Filter results using

.SH SEE ALSO
The following resources provide additional information about satori-cli:

\fBhttps://satori-ci.com/\fR
The official website for Satori CI.


.SH BUGS
No known bugs.

.SH AUTHOR
Satori CI (support@satori-ci.com)
