name: Bandit
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  satori:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          pip3 install satori-ci
          satori-cli config token $TOKEN
          satori-cli run ./ --data="{'TOKEN':'$TOKEN'} -s
